issues:
  exclude-use-default: false
linters:
  enable:
    - gocritic
    - godot
    - gofmt
    - gosec
    - ifshort
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - revive
    - stylecheck
    - unconvert
    - wastedassign
